Feature/MMS-52
ThePusketeers/MultiMathSolver pull request #15
Opened 2024-05-09 21:40 UTC by feduuusha

implemented activity for limits

2024-05-09 22:19 UTC, BIBLETUM requested changes

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
Добавь статичный метод для получения интента для открытия своей активити. В ветке example оставлял пример

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +            }
Тут лучше switch case. Контекст всего приложения не стоит использовать.

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/CustomAdapter.java
Лучше назвать LimitAdapter, так как у нас еще несколько адаптеров будет

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +                "pi — число ПИ"
Это лучше вынести куда-нибудь

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +            String text = "Вычисленное решение: \n" + viewModel.getOutput().getValue();
На LiveData от вьюмодели нужно подписываться, а не просто получать как переменную. Тоже посмотри в example

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
Тут можно создать еще одну LiveData для валидации данных и метод, который ее обновляет перед каждым каждым решением

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
> +            output = new MutableLiveData<>(useCase.getFunctionLimitUseCase(expression, Double.parseDouble(parameter)));
Зачем создавать новую LiveData)) Она же уже есть, в нее нужно закидывать значения (setValue или postValue)

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +    BottomNavigationView navigationView;
Эти поля можно сделать private

2024-05-09 22:19 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
> +        if (expression.isEmpty()) expression = "sqrt(36*x^2plus7*xplus49)-6*x";
Тут можно вынести в статику строки, типа DEFAULT_PAREMETR = "+inf"

2024-05-09 22:43 UTC, feduuusha commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
Можешь поподробнее объяснить про что ты

2024-05-09 22:46 UTC, feduuusha commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +                "pi — число ПИ"
В метод? Или как вынести

2024-05-09 22:49 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +                "pi — число ПИ"
Куда угодно (в ресурсы, отдельный класс хз), просто тут оно совсем глаза мозолит

2024-05-11 23:04 UTC, BIBLETUM requested changes

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
> +    public MutableLiveData<String> getError() {
поменяй на LiveData

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
> +    }
это тут не надо))) у вьюмодели есть метод onCleared, там делаешь compositeDisposable.clear()

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
> +                    response = response.substring(response.lastIndexOf('=') + 1);
вот это бы тоже на всякий в try catch обернуть и тоже в лайвдату ошибку пихать, в случае чего

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
> +                    parameterDoubleValue = Double.NEGATIVE_INFINITY;
Это так и должно лежать в catch?

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +    }
Ну и это убрать

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +        }) );
вынеси это в приватный метод, типа observeViewModel

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +        button.setOnClickListener(button -> viewModel.solve(parameter.getText().toString(), limit.getText().toString().replace("+", "plus")));
Это тоже в отдельный метод типа setUpListeners

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +        });
Тоже в метод

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/res/layout/activity_for_limits.xml
> +        app:layout_constraintTop_toBottomOf="@+id/limit_input" />
Посмотри, почему-то кнопка никак не реагирует на нажатие, в плане макета, непонятно, нажалась или нет

2024-05-11 23:04 UTC, BIBLETUM commented on app/src/main/res/layout/activity_for_limits.xml
Можно сюда добавить progressBar изначально невидимый, и во вьюмодели еще одну лайвдату с чем-то типа isProgress, и где с RX запрос делаем в doOnSubscribe и doAfterTerminate обновлять лайвдату. На активити, соответственно, подписываться и устанавливать visibility у progressBar

2024-05-11 23:06 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivityViewModel.java
> +    public MutableLiveData<String> getError() {
Чтоб из активити нельзя было в нее устанавливать значения

2024-05-12 19:52 UTC, BIBLETUM approved these changes

2024-05-13 07:57 UTC, merged