Feature/mms 48
ThePusketeers/MultiMathSolver pull request #18
Opened 2024-05-20 20:43 UTC by Archemalit

Done tasks 47-49, 60. It remains only to decide how to enlarge the pictures on the three buttons.

2024-05-21 10:54 UTC, BIBLETUM requested changes

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/res/layout/activity_for_booleanalgebra.xml
> +        app:layout_constraintTop_toBottomOf="@+id/title" />
Тут можно отключить ввод с клавиатуры android:focusable="false". Также можно сделать само поле и шрифты побольше.

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/res/layout/activity_for_booleanalgebra.xml
Посмотри constraintlayout chains, чтоб получше расположить элементы на экране

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                Intent intent = new Intent(view.getContext(), BooleanAlgebraSolvedActivity.class);
У тебя же есть статичный метод в BooleanAlgebraSolvedActivity для создания интента, почему бы не использовать его

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraSolvedActivity.java
> +    }
В этот метод добавить в получаемые переменные строку, тут же в интент класть её

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraSolvedActivity.java
> +
Сюда можно в статику вынести константу имени extra из интента ("expression")

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraAdapter.java
> +        String [] dataBooleanAlgebra = new String[] {"СКНФ: ", "СДНФ: ", "Тупиковые ДНФ: ", "Минимальная ДНФ: ", "Сокращённая ДНФ: ", "Полином Жегалкина: ", "Классификация Поста: "};
Это можно вынести в константы

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraAdapter.java
> +    }
Передавать в конструктор data не стоит.
Лучше создать метод типа "submitData" и там передавать данные, также нужно будет вызвать notifydatasetchanged()

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraSolvedActivity.java
> +        }
Это лучше вынести в отдельный метод

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraViewModel.java
> +    public List<String> solve(String expression) throws IncorrectFunctionInput {
Почему бы тут не использовать 2 LiveData: одна для ответа, вторая для ошибок, а в активити на них подписываться. Как у Федора в Feature/MMS-52

2024-05-21 10:54 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                startActivity(new Intent(BooleanAlgebraActivity.this, LimitActivity.class)); // заменить MainActivity2 на класс для Дискры
Тут тоже лучше получать интент из статичного метода в LimitActivity

2024-05-21 23:55 UTC, Archemalit commented on app/src/main/res/layout/activity_for_booleanalgebra.xml
> +        app:layout_constraintTop_toBottomOf="@+id/title" />
Исправлено

2024-05-21 23:58 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                Intent intent = new Intent(view.getContext(), BooleanAlgebraSolvedActivity.class);
Готово

2024-05-22 00:00 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraSolvedActivity.java
> +    }
Готово

2024-05-22 00:08 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraSolvedActivity.java
> +
Готово

2024-05-22 00:33 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraSolvedActivity.java
> +        }
Готово

2024-05-22 10:39 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraViewModel.java
> +    public List<String> solve(String expression) throws IncorrectFunctionInput {
Готово

2024-05-22 11:46 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraAdapter.java
> +        String [] dataBooleanAlgebra = new String[] {"СКНФ: ", "СДНФ: ", "Тупиковые ДНФ: ", "Минимальная ДНФ: ", "Сокращённая ДНФ: ", "Полином Жегалкина: ", "Классификация Поста: "};
Готово

2024-05-24 09:23 UTC, Archemalit commented on app/src/main/res/layout/activity_for_booleanalgebra.xml
Готово

2024-05-24 09:30 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                startActivity(new Intent(BooleanAlgebraActivity.this, LimitActivity.class)); // заменить MainActivity2 на класс для Дискры
Готово

2024-05-24 11:23 UTC, BIBLETUM requested changes
Еще запрети поворот экрана, а то тогда весь макет ломается

2024-05-24 11:23 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
>  }
Это нужно в классе BooleanAlgebraSolvedActivity прописать, а не тут

2024-05-24 11:23 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                Intent intent = newIntent(view.getContext(), expression);
тут newIntent вызывать у BooleanAlgebraSolvedActivity

2024-05-24 11:23 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraAdapter.java
Тут пофиксить синие/белые цвета

2024-05-25 07:10 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraAdapter.java
Готово

2024-05-25 07:10 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                Intent intent = newIntent(view.getContext(), expression);
Готово

2024-05-25 07:10 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
>  }
Готово

2024-05-25 14:12 UTC, BIBLETUM requested changes

2024-05-25 14:12 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                Intent intent = newIntentSolved(view.getContext(), expression);
тут нужен context BooleanAlgebraActivity, а не вьюшки

2024-05-25 14:12 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +//    }
Закоменченное нужно убрать

2024-05-25 14:15 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +//    }
Готово

2024-05-25 14:17 UTC, Archemalit commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
> +                Intent intent = newIntentSolved(view.getContext(), expression);
Готово

2024-05-25 14:18 UTC, merged