Feature/mms 55
ThePusketeers/MultiMathSolver pull request #20
Opened 2024-06-01 16:59 UTC by robl0xx

help pls((

2024-06-01 21:22 UTC, BIBLETUM requested changes

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +                startActivity(new Intent(LimitActivity.this, MatrixActivity.class)); // заменить MainActivity2 на класс для Матриц
Ты же сделал статический метод для получения интента в MatrixActivity, почему не используешь его тут

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
Тут тоже нужно использовать статичный метод из MatrixActivity

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    private final MatrixActivityViewModel viewModel = new MatrixActivityViewModel();
ViewModel нужно получать через ViewModelProvider в методе onCreate

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/res/layout/table_view_cell_layout.xml
Попробуй установить минимальную ширину айтема, чтоб все cell были одного размера, либо попробовать это сделать через adapter

2024-06-01 21:22 UTC, BIBLETUM commented on build.gradle.kts
Оставь ты его уже 8.3.1))) А то у всех версия 8.3.1 и каждый раз приходится синхронизировать проект

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/res/layout/activity_matrix.xml
Можно пересмотреть макет, сделать его более удобным, возможно добавить выпадающие списки или radiobutton. Также сейчас элементы установлены не ровно

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/res/layout/activity_matrix.xml
> +        tools:ignore="MissingConstraints" />
Можно установить значение по умолчанию, 0 или 1

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MyTableViewAdapter.java
Переименуй в MatrixAdapter и почисти комменты

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivityViewModel.java
> +    MutableLiveData<MatrixOperations> outputMatrix = new MutableLiveData<>();
Эти MuatableLiveData должны быть приватными, а то из других мест можно будет устанавливать значения, а наружу должны торчать просто LiveData

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivityViewModel.java
Также нужно добавить обработку ошибок, соответственно, еще одну LiveData

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    public static void matrixParserFromArrayToTable(MyTableViewAdapter myTableViewAdapter, MatrixOperations matrixOperations){
Зачем тут статика

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    public static double[][] matrixParserFromTableToArray(MyTableViewAdapter myTableViewAdapter){
Зачем тут статика

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    }
Используй статические методы из других активити. Подтяни с дева, если у тебя их нет

2024-06-01 21:22 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +                determinantDisplay.setText(String.valueOf(viewModel.determinant.getValue()));
Ко всему относится: не нужно напрямую обращаться к viewModel.determinant.getValue(), у тебя же тут уже есть конкретный параметр ints. Также можешь попробовать использовать лямбды, с ними проще

2024-06-02 05:36 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/LimitActivity.java
> +                startActivity(new Intent(LimitActivity.this, MatrixActivity.class)); // заменить MainActivity2 на класс для Матриц
теперь использую

2024-06-02 05:37 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/BooleanAlgebraActivity.java
исправил

2024-06-02 05:42 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    private final MatrixActivityViewModel viewModel = new MatrixActivityViewModel();
сделал инициализацию вьюмоедли и адаптера в onCreate

2024-06-02 05:50 UTC, robl0xx commented on app/src/main/res/layout/table_view_cell_layout.xml
сделал

2024-06-02 05:52 UTC, robl0xx commented on build.gradle.kts
у меня 8.3.1 не поддерживается

2024-06-02 05:55 UTC, robl0xx commented on app/src/main/res/layout/activity_matrix.xml
> +        tools:ignore="MissingConstraints" />
установил 1

2024-06-02 05:59 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MyTableViewAdapter.java
сделал

2024-06-02 06:05 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivityViewModel.java
> +    MutableLiveData<MatrixOperations> outputMatrix = new MutableLiveData<>();
сделал

2024-06-02 06:09 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    public static void matrixParserFromArrayToTable(MyTableViewAdapter myTableViewAdapter, MatrixOperations matrixOperations){
убрал

2024-06-02 06:09 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    public static double[][] matrixParserFromTableToArray(MyTableViewAdapter myTableViewAdapter){
убрал

2024-06-02 06:32 UTC, robl0xx commented on app/src/main/res/layout/activity_matrix.xml
что то двигал как мог

2024-06-02 09:25 UTC, robl0xx commented on build.gradle.kts
сделал

2024-06-02 10:06 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +    }
даже после мерджа из дева не видит никакой статики

2024-06-02 10:07 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivityViewModel.java
лайв дату создал, обсервер сделал

2024-06-02 10:07 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/presentation/MatrixActivity.java
> +                determinantDisplay.setText(String.valueOf(viewModel.determinant.getValue()));
исправил

2024-06-03 18:00 UTC, BIBLETUM approved these changes

2024-06-04 13:50 UTC, merged