Feature/mms 43
ThePusketeers/MultiMathSolver pull request #5
Opened 2024-04-14 18:53 UTC by robl0xx

add SLAY solution without tests

2024-04-16 12:38 UTC, BIBLETUM requested changes
Надо бы починить архитектуру

2024-04-16 12:38 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/domain/Repository.java
> +import com.example.multimathsolver.data.slay.SLAY;
domain слой не должен знать ни о каком другом слое

2024-04-16 12:38 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/domain/Repository.java
> +    public String solutionOfSLAY(SLAY matrix);
модификатор public можно убрать, метод лучше назвать "getSolutionOfSLAY"

2024-04-16 12:38 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/domain/GetSLAYSolutionUseCase.java
> +import com.example.multimathsolver.data.slay.SLAY;
Опять же domain импортирует что-то из data, такого быть не должно

2024-04-16 12:38 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/slay/SLAY.java
> +//    private static void enterRow(Matrix mat, int row) {
Закоментированное нужно убрать

2024-04-16 12:38 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
Почему бы не вынести класс SLAY в domain, оставив в нем только поля, а сами методы реализовывать в RepositoryIMPL. Либо можно оставить, как есть, но добавить в domain слой SLAYModel, которая будет содержать только поля, а в data уже реализовать какой-то mapper, который SLAYModel мапит в SLAY.

2024-04-16 15:34 UTC, rbrmnv commented on app/src/main/java/com/example/multimathsolver/domain/Repository.java
> +import com.example.multimathsolver.data.slay.SLAY;
исправил

2024-04-16 15:34 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/domain/Repository.java
> +    public String solutionOfSLAY(SLAY matrix);
исправил

2024-04-16 15:34 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/domain/GetSLAYSolutionUseCase.java
> +import com.example.multimathsolver.data.slay.SLAY;
исправил

2024-04-16 15:34 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
сделал первый предложенный тобой вариант

2024-04-17 16:27 UTC, BIBLETUM requested changes

2024-04-17 16:27 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +import java.util.Scanner;
Не совсем понимаю, зачем нам нужен Scan

2024-04-17 16:27 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +
Можно поменьше пустых строк)))

2024-04-17 16:27 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
Зачем мы выводим и считываем что-то с консоли, у нас же мобильное приложение, не консольное. Если нужны какие-то логи, нужно использовать Log.d

2024-04-17 16:27 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +
Этот код нужен? Это же просто статика, на которую никто не ссылается. Опять же зачем нам работа с консолью). Если это все-таки нужно, то необходимо убрать статику и консольные фичи

2024-04-17 19:27 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +
убрал

2024-04-17 19:27 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
понял

2024-04-17 19:27 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +
сори))))

2024-04-17 19:28 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +import java.util.Scanner;
теперь не нужен, так как убрал статику

2024-04-18 16:10 UTC, BIBLETUM requested changes
Еще подтяни изменения с dev

2024-04-18 16:10 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/domain/SLAY.java
> +import static com.example.multimathsolver.data.RepositoryImpl.getDeepCopyOfArray;
Все равно в domain лежит data, так еще и статик)

2024-04-18 16:10 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +    }
Этот метод можно сделать приватным без статики и использовать его уже здесь, а не в domain

2024-04-18 16:10 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/domain/SLAY.java
> +    }
Либо здесь без статики прописать всю логику getDeepCopyOfArray

2024-04-19 06:04 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/domain/SLAY.java
> +import static com.example.multimathsolver.data.RepositoryImpl.getDeepCopyOfArray;
исправил(((((((

2024-04-19 06:05 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +    }
я пересмотрел логику, и убрал его

2024-04-19 06:15 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/domain/SLAY.java
> +    }
так и сделал

2024-04-19 06:16 UTC, robl0xx commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +    }
сделал

2024-04-19 11:57 UTC, BIBLETUM approved these changes

2024-04-19 18:12 UTC, merged