All tasks about operations with matrix are done, except MMS-22.
ThePusketeers/MultiMathSolver pull request #7
Opened 2024-04-16 13:10 UTC by Archemalit

2024-04-16 13:18 UTC, BIBLETUM requested changes
Поменяй snake_case на CamelCase везде

2024-04-16 13:18 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
> +//        else if (this.rows == other_matrix.columns) {
Неиспользуемый код в комментариях нужно убрать

2024-04-16 13:18 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/data/RepositoryImpl.java
Поменяй название переменных на CamelCase

2024-04-16 13:18 UTC, BIBLETUM commented on app/src/main/java/com/example/multimathsolver/domain/Repository.java
Тоже CamelCase

2024-04-17 06:22 UTC, Archemalit commented
всё исправлено

2024-04-17 16:11 UTC, BIBLETUM approved these changes
LGTM

2024-04-17 17:07 UTC, merged